Cree handler y controller de getUsers
GregoHouse/m-ser pull request #4
Opened 2023-06-16 01:35 UTC by jkapa7

2023-06-16 12:59 UTC, XCODE89 approved these changes, later dismissed

2023-06-16 16:19 UTC, Aegox approved these changes

2023-06-16 17:20 UTC, Aegox requested changes
En el handler no estas pasandole los argumentos de req y res

2023-06-17 15:59 UTC, Aegox approved these changes

2023-06-17 15:59 UTC, Aegox approved these changes

2023-06-18 05:05 UTC, XCODE89 approved these changes

2023-06-18 14:55 UTC, merged